# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efde7bff9289bb695651e97f1b56cdd72f86c3f192b662552cb0ad369a2a36d2631ba727d772e2abe4a11e6dcb16446fdbe22048f8d6737b27f4663312cec7fe

test:
  secret_key_base: 039625fa6eccdf92460225f79df1bf9b34a27e4642a6059004cca4175a55e622eef78f4a782b71459343e4400ee0071105829a5dd0394c728c1d0705691fa63d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
